// Optional end-to-end check. Requires Playwright and Chrome; neither is a runtime dependency.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'node:net';
import { spawn, execFileSync } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const folder = await mkdtemp(join(tmpdir(), 'plant-journal-browser-'));
const artifacts = process.env.PLANT_ARTIFACTS || folder;
await mkdir(artifacts, { recursive: true });
const listener = createServer();
await new Promise(r => listener.listen(0, '127.0.0.1', r));
const port = listener.address().port;
await new Promise(r => listener.close(r));
const config = join(folder, 'config.toml');
await writeFile(config, `bind = "127.0.0.1:${port}"\nsecure_cookies = false\ndata_dir = ${JSON.stringify(join(folder, 'data'))}\n`);
const server = spawn(resolve(process.env.PLANT_BINARY || 'target/debug/plant-journal'), [], {env:{...process.env,PLANT_CONFIG:config},stdio:['ignore','pipe','pipe']});
let serverLog = '';
server.stdout.on('data', b => serverLog += b);
server.stderr.on('data', b => serverLog += b);
let launchError;
server.on('error', error => { launchError = error; });
const base = `http://127.0.0.1:${port}`;
let browser;
try {
  for (let i=0;i<100;i++) {
    if(launchError)throw launchError;
    if(server.exitCode !== null)throw new Error(serverLog);
    try {if((await fetch(base+'/healthz')).ok)break;}catch(_){}
    await new Promise(r=>setTimeout(r,100));
  }
  browser = await chromium.launch({channel:'chrome',headless:true});
  const visitor = await browser.newPage();
  await visitor.goto(base+'/signup');
  await visitor.getByLabel('Email',{exact:true}).fill('browser@example.com');
  await visitor.getByLabel('Password',{exact:true}).fill('Browser testing passphrase');
  await visitor.getByRole('button',{name:'Create account',exact:true}).click();
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.getByRole('button',{name:'Sign out',exact:true}).click();
  await visitor.waitForURL(base+'/login');
  await visitor.getByLabel('Email',{exact:true}).fill('browser@example.com');
  await visitor.getByLabel('Password',{exact:true}).fill('Browser testing passphrase');
  await visitor.getByRole('button',{name:'Sign in',exact:true}).click();
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  // Fixture session for the migrated garden, whose local simulated hardware is
  // exercised below. This writes only the test's temporary SQLite database.
  const token='b'.repeat(64);
  execFileSync('python3',['-c',`import sqlite3,hashlib,sys,time
with sqlite3.connect(sys.argv[1]) as db:
 db.execute("INSERT INTO sessions(token_hash,user_id,garden_id,expires_at) VALUES(?,?,?,?)",(hashlib.sha256(sys.argv[2].encode()).hexdigest(),"00000000-0000-0000-0000-000000000002","00000000-0000-0000-0000-000000000001",int(time.time())+3600))`,join(folder,'data','journal.sqlite3'),token]);
  const context = await browser.newContext({viewport:{width:1440,height:1050}});
  const page = await context.newPage();
  await page.context().addCookies([{name:'plant_session',value:token,url:base,httpOnly:true,sameSite:'Lax'}]);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  const go = async path => {await page.goto(base+path);await page.locator('#content[aria-busy="false"]').waitFor();assert.equal(await page.locator('#notice.error').count(),0);};
  const closed = async () => page.locator('dialog').waitFor({state:'hidden'});
  const dialog = () => page.locator('dialog');
  const uploadAndDelete = async () => {
    await page.getByRole('button', {name:'Add photo', exact:true}).first().click();
    await dialog().getByLabel('Photo', {exact:true}).setInputFiles({name:'photo.gif', mimeType:'image/gif', buffer:Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==','base64')});
    await dialog().getByRole('button', {name:'Upload photo', exact:true}).click();await closed();
    await page.locator('.photo-card img').waitFor();
    await page.locator('.photo-card img').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>{const img=document.querySelector('.photo-card img');return img?.complete && img.naturalWidth===1;});
    await page.reload();await page.locator('.photo-card img').waitFor();
    await page.locator('.photo-card').getByRole('button', {name:'Delete',exact:true}).click();
    await dialog().getByRole('button', {name:'Delete permanently',exact:true}).click();await closed();
    await page.locator('.photo-card').waitFor({state:'hidden'});
  };
  await go('/settings');
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'fieldnotes');
  const defaultPaper = await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor);
  await page.getByLabel('Theme', {exact:true}).selectOption('arcade');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'arcade');
  assert.notEqual(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), defaultPaper);
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'arcade');
  const themeTab = await page.context().newPage();
  await themeTab.goto(base+'/login');
  assert.equal(await themeTab.locator('html').getAttribute('data-theme'), 'arcade');
  await page.getByLabel('Theme', {exact:true}).selectOption('fieldnotes');
  await themeTab.waitForFunction(() => document.documentElement.dataset.theme === 'fieldnotes');
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), defaultPaper);
  await page.evaluate(() => localStorage.setItem('fieldnotes.theme', 'unknown-theme'));
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'fieldnotes');
  await themeTab.close();
  // Storage restrictions must not prevent switching the current page's theme.
  await page.evaluate(() => {
    window.originalSetItem = Storage.prototype.setItem;
    Storage.prototype.setItem = () => {throw new DOMException('Storage blocked', 'SecurityError');};
  });
  await page.getByLabel('Theme', {exact:true}).selectOption('arcade');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'arcade');
  await page.getByText('Theme applied for this page. Browser storage is unavailable, so it could not be saved.').waitFor();
  await page.evaluate(() => {Storage.prototype.setItem = window.originalSetItem;delete window.originalSetItem;});
  await page.getByLabel('Theme', {exact:true}).selectOption('fieldnotes');
  await page.getByRole('button',{name:'Add collaborator',exact:true}).click();
  await dialog().getByLabel('Account email').fill('browser@example.com');
  await dialog().getByRole('button',{name:'Add collaborator',exact:true}).click();await closed();
  await page.getByText('browser@example.com',{exact:true}).waitFor();
  await visitor.reload();await visitor.locator('#content[aria-busy="false"]').waitFor();
  await Promise.all([visitor.waitForNavigation(), visitor.getByLabel('Your garden',{exact:true}).selectOption('00000000-0000-0000-0000-000000000001')]);
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.goto(base+'/settings');await visitor.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await visitor.getByRole('button',{name:'Add collaborator',exact:true}).count(),0);
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await dialog().getByRole('button',{name:'Remove collaborator',exact:true}).click();await closed();
  await visitor.close();
  await go('/strains');
  assert.equal(await page.locator('.strain-card').count(),152);
  assert.equal(await page.locator('.strain-card.is-collected').count(),0);
  await page.getByLabel('Find a strain',{exact:true}).fill('Blue Dream');
  await page.getByRole('link',{name:'Blue Dream · Not collected',exact:true}).click();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  assert.equal(await page.locator('.lineage-node').count(),3);
  await page.getByRole('button',{name:'♡ Add to wishlist',exact:true}).click();
  await page.getByText('Wishlist updated.',{exact:true}).waitFor();
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  await page.getByRole('link',{name:'Blue Dream · Wanted',exact:true}).waitFor();
  await page.getByRole('button',{name:'✦ Mark collected',exact:true}).click();
  await page.getByText('Strain collected. Your card is unlocked.',{exact:true}).waitFor();
  assert.equal(await page.locator('.strain-card.is-collected').count(),1);
  await go('/strains');
  await page.getByRole('button',{name:'+ Add a strain',exact:true}).click();
  await dialog().getByLabel('Strain name',{exact:true}).fill('Browser cross');
  await dialog().getByLabel('Species',{exact:true}).fill('Test plant');
  await dialog().getByLabel('Collection status',{exact:true}).selectOption('wanted');
  await dialog().getByLabel('Parent 1',{exact:true}).selectOption({label:'Blue Dream'});
  await dialog().getByLabel('Parent 2',{exact:true}).selectOption({label:'Gelato'});
  await dialog().getByRole('button',{name:'Save strain',exact:true}).click();await closed();
  await page.getByLabel('Find a strain',{exact:true}).fill('Browser cross');
  await page.getByRole('link',{name:'Browser cross · Wanted',exact:true}).click();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  await page.getByLabel('Generations',{exact:true}).selectOption('3');
  assert.ok(await page.locator('.lineage-node').count()>=7);
  await page.getByRole('button',{name:'Zoom in ancestry',exact:true}).click();
  await page.getByRole('button',{name:'Fit graph',exact:true}).click();
  await page.screenshot({path:join(artifacts,'strain-ancestry-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Ancestry detail overflows mobile');
  await page.getByRole('button',{name:'Fit graph',exact:true}).click();
  await page.screenshot({path:join(artifacts,'strain-ancestry-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1050});
  await page.getByRole('link',{name:'Explore Blue Dream ancestry',exact:true}).click();
  await page.locator('h1').filter({hasText:'Blue Dream'}).waitFor();
  await go('/strains');
  await page.getByLabel('Show cards',{exact:true}).selectOption('wanted');
  assert.equal(await page.locator('.strain-card').count(),1);
  await page.getByLabel('Show cards',{exact:true}).selectOption('all');
  await page.screenshot({path:join(artifacts,'strain-collection-desktop.png'),fullPage:false});
  await go('/seeds');
  await page.getByRole('button',{name:'+ Add your first seeds',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tomato <seed>');
  await dialog().getByLabel('Variety',{exact:true}).fill("O'Brien's Purple");
  await dialog().getByLabel('Quantity on hand').fill('3');
  await dialog().getByLabel('Supplier').fill('Seed library');
  await dialog().getByLabel('Purchase year').fill('2026');
  await dialog().getByLabel('Storage location').fill('Fridge');
  await dialog().getByLabel('Notes',{exact:true}).fill('Sow indoors.');
  await dialog().getByLabel('Strain',{exact:true}).fill('Typed browser strain');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByText('3 packets',{exact:true}).waitFor();
  await page.getByRole('link',{name:'◇ Typed browser strain',exact:true}).waitFor();
  await uploadAndDelete();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Quantity on hand').fill('0');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Seed inventory overflows mobile viewport');
  await page.screenshot({path:join(artifacts,'seeds-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Your next season starts here',exact:true}).waitFor();
  await page.setViewportSize({width:1440,height:1050});
  await go('/plants');
  await page.getByRole('button',{name:'+ Add your first plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Monstera');
  await dialog().getByLabel('Species or variety').fill('Monstera deliciosa');
  await dialog().getByLabel('Strain',{exact:true}).fill('Browser cross');
  await dialog().getByLabel('Plant notes').fill('New leaves near the grow light.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByRole('heading',{name:'Photo history',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  await page.getByRole('link',{name:'◇ Browser cross',exact:true}).waitFor();
  await uploadAndDelete();
  await go('/plants');
  await page.getByRole('button',{name:'+ Add a plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Pothos');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/journal');
  await page.getByRole('button',{name:'+ Add an entry',exact:true}).click();
  await dialog().getByLabel('Entry type').selectOption('watering');
  await dialog().getByLabel('Monstera',{exact:true}).check();
  await dialog().getByLabel('Pothos',{exact:true}).check();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. New leaf on the monstera.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Watered both plants by hand. New leaf on the monstera.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. Soil drains well.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/photos');
  await page.getByRole('button',{name:'▧ Capture now',exact:true}).click();
  await page.locator('.photo-card img').waitFor();
  assert.equal(await page.locator('.photo-card .plant-tags .badge').count(),2);
  await page.getByRole('button',{name:'Link plants',exact:true}).click();
  await dialog().getByLabel('Pothos',{exact:true}).uncheck();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.waitForFunction(()=>document.querySelectorAll('.photo-card .plant-tags .badge').length===1);
  await go('/calendar');
  await page.locator('.day.today').click();
  await page.locator('#day-events').getByText('Watered both plants by hand. Soil drains well.',{exact:true}).first().waitFor();
  await page.getByLabel('Filter by event type').selectOption('photo');
  await page.waitForFunction(()=>document.querySelectorAll('#day-events .timeline li').length===1);
  await page.screenshot({path:join(artifacts,'calendar-desktop.png'),fullPage:true});
  await go('/environment');
  assert.equal(await page.locator('svg.chart').count(),2);
  await page.getByLabel('Reading range').selectOption('168');
  await go('/equipment');
  await page.getByRole('button',{name:'+ Add outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tent light');
  await dialog().getByRole('button',{name:'Add outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tent light',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Enable daily schedule').isChecked(),false);
  await page.getByRole('button',{name:'On…',exact:true}).click();
  await dialog().getByRole('button',{name:'Apply override',exact:true}).click();await closed();
  await page.getByText('Output on',{exact:true}).waitFor({timeout:35000});
  await page.getByRole('button',{name:'Resume schedule',exact:true}).click();
  await page.getByText('Output off',{exact:true}).waitFor({timeout:35000});
  await page.getByLabel('On at').fill('20:00');
  await page.getByLabel('Off at').fill('06:00');
  await page.getByRole('button',{name:'Save schedule',exact:true}).click();
  await page.getByText('Schedule saved. It will apply on the next control cycle.').waitFor();
  await page.getByRole('button',{name:'Edit outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Grow light');
  await dialog().getByRole('button',{name:'Save outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Grow light',exact:true}).waitFor();
  await go('/settings');
  await page.getByLabel('Take one photo every day').check();
  await page.getByLabel('Capture time').fill('13:00');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved.',{exact:true}).waitFor();
  await go('/');
  await page.screenshot({path:join(artifacts,'overview-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  for(const path of ['/','/plants','/strains','/journal','/calendar','/photos','/environment','/equipment','/settings']) {
    await go(path);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`Mobile overflow on ${path}`);
  }
  await go('/calendar');await page.screenshot({path:join(artifacts,'calendar-mobile.png'),fullPage:true});
  await go('/settings');
  await page.getByLabel('Theme', {exact:true}).selectOption('arcade');
  for (const width of [1440,390]) {
    await page.setViewportSize({width,height:width===390?844:1050});
    for (const path of ['/','/plants','/seeds','/strains','/journal','/calendar','/photos','/environment','/equipment','/settings']) {
      await go(path);
      assert.equal(await page.locator('html').getAttribute('data-theme'), 'arcade');
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Night Arcade overflow at ${width}px on ${path}`);
      if (['/','/strains','/settings','/calendar','/environment'].includes(path)) {
        await page.screenshot({path:join(artifacts,`arcade-${path.slice(1)||'overview'}-${width}.png`),fullPage:path!=='/strains'});
      }
    }
  }
  await go('/plants');
  await page.locator('.plant-card').filter({has:page.getByRole('link',{name:'Monstera',exact:true})}).getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Archive plant (keep its history)').check();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByText('Archived · history retained',{exact:true}).waitFor();
  await page.getByText('Watered both plants by hand. Soil drains well.',{exact:true}).waitFor();
  await go('/photos');
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Watch the changes unfold',exact:true}).waitFor();
  assert.deepEqual(errors,[],`Browser errors: ${errors.join('\n')}`);
  console.log(`Browser workflows passed on desktop and mobile. Screenshots: ${artifacts}`);
} catch(error) {
  console.error(serverLog);
  throw error;
} finally {
  await browser?.close();
  server.kill('SIGTERM');
  await new Promise(r=>server.exitCode===null?server.once('exit',r):r());
}
