// Optional end-to-end check. Requires Playwright and Chrome; neither is a runtime dependency.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'node:net';
import { spawn } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const folder = await mkdtemp(join(tmpdir(), 'plant-journal-browser-'));
const artifacts = process.env.PLANT_ARTIFACTS || folder;
await mkdir(artifacts, { recursive: true });
const listener = createServer();
await new Promise(r => listener.listen(0, '127.0.0.1', r));
const port = listener.address().port;
await new Promise(r => listener.close(r));
const config = join(folder, 'config.toml');
await writeFile(config, `bind = "127.0.0.1:${port}"\ndata_dir = ${JSON.stringify(join(folder, 'data'))}\n`);
const server = spawn(resolve(process.env.PLANT_BINARY || 'target/debug/plant-journal'), [], {env:{...process.env,PLANT_CONFIG:config},stdio:['ignore','pipe','pipe']});
let serverLog = '';
server.stdout.on('data', b => serverLog += b);
server.stderr.on('data', b => serverLog += b);
let launchError;
server.on('error', error => { launchError = error; });
const base = `http://127.0.0.1:${port}`;
let browser;
try {
  for (let i=0;i<100;i++) {
    if(launchError)throw launchError;
    if(server.exitCode !== null)throw new Error(serverLog);
    try {if((await fetch(base+'/api/v1/summary')).ok)break;}catch(_){}
    await new Promise(r=>setTimeout(r,100));
  }
  browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  const go = async path => {await page.goto(base+path);await page.locator('#content[aria-busy="false"]').waitFor();assert.equal(await page.locator('#notice.error').count(),0);};
  const closed = async () => page.locator('dialog').waitFor({state:'hidden'});
  const dialog = () => page.locator('dialog');
  await go('/seeds');
  await page.getByRole('button',{name:'+ Add your first seeds',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tomato <seed>');
  await dialog().getByLabel('Variety',{exact:true}).fill("O'Brien's Purple");
  await dialog().getByLabel('Quantity on hand').fill('3');
  await dialog().getByLabel('Supplier').fill('Seed library');
  await dialog().getByLabel('Purchase year').fill('2026');
  await dialog().getByLabel('Storage location').fill('Fridge');
  await dialog().getByLabel('Notes',{exact:true}).fill('Sow indoors.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByText('3 packets',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Quantity on hand').fill('0');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Seed inventory overflows mobile viewport');
  await page.screenshot({path:join(artifacts,'seeds-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Your next season starts here',exact:true}).waitFor();
  await page.setViewportSize({width:1440,height:1050});
  await go('/plants');
  await page.getByRole('button',{name:'+ Add your first plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Monstera');
  await dialog().getByLabel('Species or variety').fill('Monstera deliciosa');
  await dialog().getByLabel('Plant notes').fill('New leaves near the grow light.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).waitFor();
  await page.getByRole('button',{name:'+ Add a plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Pothos');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/journal');
  await page.getByRole('button',{name:'+ Add an entry',exact:true}).click();
  await dialog().getByLabel('Entry type').selectOption('watering');
  await dialog().getByLabel('Monstera',{exact:true}).check();
  await dialog().getByLabel('Pothos',{exact:true}).check();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. New leaf on the monstera.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Watered both plants by hand. New leaf on the monstera.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. Soil drains well.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/photos');
  await page.getByRole('button',{name:'▧ Capture now',exact:true}).click();
  await page.locator('.photo-card img').waitFor();
  assert.equal(await page.locator('.photo-card .plant-tags .badge').count(),2);
  await page.getByRole('button',{name:'Link plants',exact:true}).click();
  await dialog().getByLabel('Pothos',{exact:true}).uncheck();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.waitForFunction(()=>document.querySelectorAll('.photo-card .plant-tags .badge').length===1);
  await go('/calendar');
  await page.locator('.day.today').click();
  await page.locator('#day-events').getByText('Watered both plants by hand. Soil drains well.',{exact:true}).first().waitFor();
  await page.getByLabel('Filter by event type').selectOption('photo');
  await page.waitForFunction(()=>document.querySelectorAll('#day-events .timeline li').length===1);
  await page.screenshot({path:join(artifacts,'calendar-desktop.png'),fullPage:true});
  await go('/environment');
  assert.equal(await page.locator('svg.chart').count(),2);
  await page.getByLabel('Reading range').selectOption('168');
  await go('/equipment');
  await page.getByRole('button',{name:'+ Add outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tent light');
  await dialog().getByRole('button',{name:'Add outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tent light',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Enable daily schedule').isChecked(),false);
  await page.getByRole('button',{name:'On…',exact:true}).click();
  await dialog().getByRole('button',{name:'Apply override',exact:true}).click();await closed();
  await page.getByText('Output on',{exact:true}).waitFor({timeout:35000});
  await page.getByRole('button',{name:'Resume schedule',exact:true}).click();
  await page.getByText('Output off',{exact:true}).waitFor({timeout:35000});
  await page.getByLabel('On at').fill('20:00');
  await page.getByLabel('Off at').fill('06:00');
  await page.getByRole('button',{name:'Save schedule',exact:true}).click();
  await page.getByText('Schedule saved. It will apply on the next control cycle.').waitFor();
  await page.getByRole('button',{name:'Edit outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Grow light');
  await dialog().getByRole('button',{name:'Save outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Grow light',exact:true}).waitFor();
  await go('/settings');
  await page.getByLabel('Take one photo every day').check();
  await page.getByLabel('Capture time').fill('13:00');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved.',{exact:true}).waitFor();
  await go('/');
  await page.screenshot({path:join(artifacts,'overview-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  for(const path of ['/','/plants','/journal','/calendar','/photos','/environment','/equipment','/settings']) {
    await go(path);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`Mobile overflow on ${path}`);
  }
  await go('/calendar');await page.screenshot({path:join(artifacts,'calendar-mobile.png'),fullPage:true});
  await go('/plants');
  await page.locator('.plant-card').filter({has:page.getByRole('link',{name:'Monstera',exact:true})}).getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Archive plant (keep its history)').check();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByText('Archived · history retained',{exact:true}).waitFor();
  await page.getByText('Watered both plants by hand. Soil drains well.',{exact:true}).waitFor();
  await go('/photos');
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Watch the changes unfold',exact:true}).waitFor();
  assert.deepEqual(errors,[],`Browser errors: ${errors.join('\n')}`);
  console.log(`Browser workflows passed on desktop and mobile. Screenshots: ${artifacts}`);
} catch(error) {
  console.error(serverLog);
  throw error;
} finally {
  await browser?.close();
  server.kill('SIGTERM');
  await new Promise(r=>server.exitCode===null?server.once('exit',r):r());
}
