// Optional end-to-end check. Requires Playwright and Chrome; neither is a runtime dependency.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'node:net';
import { spawn, execFileSync } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const folder = await mkdtemp(join(tmpdir(), 'plant-journal-browser-'));
const artifacts = process.env.PLANT_ARTIFACTS || folder;
await mkdir(artifacts, { recursive: true });
const listener = createServer();
await new Promise(r => listener.listen(0, '127.0.0.1', r));
const port = listener.address().port;
await new Promise(r => listener.close(r));
const config = join(folder, 'config.toml');
await writeFile(config, `bind = "127.0.0.1:${port}"\nsecure_cookies = false\ndata_dir = ${JSON.stringify(join(folder, 'data'))}\n`);
const server = spawn(resolve(process.env.PLANT_BINARY || 'target/debug/plant-journal'), [], {env:{...process.env,PLANT_CONFIG:config},stdio:['ignore','pipe','pipe']});
let serverLog = '';
server.stdout.on('data', b => serverLog += b);
server.stderr.on('data', b => serverLog += b);
let launchError;
server.on('error', error => { launchError = error; });
const base = `http://127.0.0.1:${port}`;
let browser;
try {
  for (let i=0;i<100;i++) {
    if(launchError)throw launchError;
    if(server.exitCode !== null)throw new Error(serverLog);
    try {if((await fetch(base+'/healthz')).ok)break;}catch(_){}
    await new Promise(r=>setTimeout(r,100));
  }
  browser = await chromium.launch({channel:'chrome',headless:true});
  const visitor = await browser.newPage();
  await visitor.goto(base+'/signup');
  await visitor.getByLabel('Email',{exact:true}).fill('browser@example.com');
  await visitor.getByLabel('Password',{exact:true}).fill('Browser testing passphrase');
  await visitor.getByRole('checkbox',{name:'Vegetables',exact:true}).waitFor();
  assert.equal(await visitor.locator('input[name="catalogs"]:checked').count(),0);
  await visitor.getByRole('checkbox',{name:'Vegetables',exact:true}).check();
  await visitor.getByRole('checkbox',{name:'Herbs',exact:true}).check();
  assert.equal(await visitor.getByRole('checkbox',{name:'Cannabis',exact:true}).isChecked(),false);
  await visitor.setViewportSize({width:390,height:844});
  assert.ok(await visitor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Signup choices overflow mobile');
  await visitor.screenshot({path:join(artifacts,'starter-collections-signup-mobile.png'),fullPage:true});
  await visitor.getByRole('button',{name:'Create account',exact:true}).click();
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.goto(base+'/strains');await visitor.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await visitor.locator('.strain-card').count(),36);
  assert.equal(await visitor.locator('.strain-card.is-collected').count(),0);
  assert.equal(await visitor.getByLabel('Plant type',{exact:true}).locator('option[value="Cannabis"]').count(),0);
  await visitor.getByLabel('Plant type',{exact:true}).selectOption('Basil');
  assert.equal(await visitor.locator('.strain-card').count(),4);
  await visitor.getByLabel('Find a variety or strain',{exact:true}).fill('Genovese');
  assert.equal(await visitor.locator('.strain-card').count(),1);
  await visitor.getByRole('link',{name:'Genovese Basil · Not collected',exact:true}).click();
  await visitor.getByRole('button',{name:'✦ Mark collected',exact:true}).click();
  await visitor.getByRole('link',{name:'Genovese Basil · Collected',exact:true}).waitFor();
  await visitor.goto(base+'/strains');await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.getByRole('button',{name:'Add starter collections',exact:true}).click();
  const starterDialog=visitor.locator('dialog');
  assert.equal(await starterDialog.getByRole('checkbox',{name:'Vegetables',exact:true}).isDisabled(),true);
  assert.equal(await starterDialog.getByRole('checkbox',{name:'Herbs',exact:true}).isDisabled(),true);
  await starterDialog.getByRole('checkbox',{name:'Flowers',exact:true}).check();
  await starterDialog.getByRole('checkbox',{name:'Fruit & berries',exact:true}).check();
  assert.ok(await starterDialog.evaluate(el=>el.scrollWidth<=el.clientWidth),'Starter collection dialog overflows mobile');
  await starterDialog.getByRole('button',{name:'Add collections',exact:true}).click();
  await starterDialog.waitFor({state:'hidden'});
  await visitor.getByText('24 cards added to your collection.',{exact:true}).waitFor();
  await visitor.reload();await visitor.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await visitor.locator('.strain-card').count(),60);
  assert.equal(await visitor.locator('.strain-card.is-collected').count(),1);
  assert.ok(await visitor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mixed collection overflows mobile');
  await visitor.setViewportSize({width:1440,height:1050});
  await visitor.screenshot({path:join(artifacts,'garden-collection-desktop.png')});
  await visitor.getByRole('button',{name:'New garden',exact:true}).click();
  await starterDialog.getByLabel('Garden name',{exact:true}).fill('Indoor plants');
  await starterDialog.getByRole('checkbox',{name:'Houseplants',exact:true}).check();
  await starterDialog.getByRole('button',{name:'Create garden',exact:true}).click();
  await visitor.waitForURL(base+'/');await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.goto(base+'/strains');await visitor.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await visitor.locator('.strain-card').count(),8);
  await visitor.getByRole('button',{name:'Sign out',exact:true}).click();
  await visitor.waitForURL(base+'/login');
  await visitor.getByLabel('Email',{exact:true}).fill('browser@example.com');
  await visitor.getByLabel('Password',{exact:true}).fill('Browser testing passphrase');
  await visitor.getByRole('button',{name:'Sign in',exact:true}).click();
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  // Fixture session for the migrated garden, whose local simulated hardware is
  // exercised below. This writes only the test's temporary SQLite database.
  const token='b'.repeat(64);
  execFileSync('python3',['-c',`import sqlite3,hashlib,sys,time
with sqlite3.connect(sys.argv[1]) as db:
 db.execute("INSERT INTO sessions(token_hash,user_id,garden_id,expires_at) VALUES(?,?,?,?)",(hashlib.sha256(sys.argv[2].encode()).hexdigest(),"00000000-0000-0000-0000-000000000002","00000000-0000-0000-0000-000000000001",int(time.time())+3600))`,join(folder,'data','journal.sqlite3'),token]);
  const context = await browser.newContext({viewport:{width:1440,height:1050}});
  const page = await context.newPage();
  await page.context().addCookies([{name:'plant_session',value:token,url:base,httpOnly:true,sameSite:'Lax'}]);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  const go = async path => {await page.goto(base+path);await page.locator('#content[aria-busy="false"]').waitFor();assert.equal(await page.locator('#notice.error').count(),0);};
  const closed = async () => page.locator('dialog').waitFor({state:'hidden'});
  const dialog = () => page.locator('dialog');
  const uploadAndDelete = async (plantName = '') => {
    await page.getByRole('button', {name:'Add photo', exact:true}).first().click();
    await dialog().getByLabel('Photo', {exact:true}).setInputFiles({name:'photo.gif', mimeType:'image/gif', buffer:Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==','base64')});
    await dialog().getByRole('button', {name:'Upload photo', exact:true}).click();await closed();
    await page.locator('.photo-card img').waitFor();
    await page.locator('.photo-card img').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>{const img=document.querySelector('.photo-card img');return img?.complete && img.naturalWidth===1;});
    if (plantName) {
      await go('/plants');
      const card=page.locator('.plant-card').filter({has:page.getByRole('link',{name:plantName,exact:true})});
      await card.locator('.plant-cover img').waitFor();
      assert.ok(await card.locator('.plant-cover img').evaluate(img=>img.complete && img.naturalWidth===1));
      await page.screenshot({path:join(artifacts,'plant-card-with-photo.png')});
      await card.getByRole('link',{name:plantName,exact:true}).click();
      await page.locator('.photo-card img').waitFor();
    }
    await page.reload();await page.locator('.photo-card img').waitFor();
    await page.locator('.photo-card').getByRole('button', {name:'Delete',exact:true}).click();
    await dialog().getByRole('button', {name:'Delete permanently',exact:true}).click();await closed();
    await page.locator('.photo-card').waitFor({state:'hidden'});
    if (plantName) {
      await go('/plants');
      const card=page.locator('.plant-card').filter({has:page.getByRole('link',{name:plantName,exact:true})});
      assert.equal(await card.locator('.plant-cover img').count(),0);
      assert.equal(await card.locator('.plant-art').count(),1);
      await card.getByRole('link',{name:plantName,exact:true}).click();
    }
  };
  await go('/settings');
  const themeIds = ['fieldnotes','arcade','herbarium','seed_catalog','solarpunk','alchemy','neon_genetics'];
  assert.deepEqual(await page.locator('#theme-select option').evaluateAll(options=>options.map(option=>option.value)),themeIds);
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'fieldnotes');
  const defaultPaper = await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor);
  await page.getByLabel('Theme', {exact:true}).selectOption('arcade');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'arcade');
  assert.notEqual(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), defaultPaper);
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'arcade');
  const themeTab = await page.context().newPage();
  await themeTab.goto(base+'/login');
  assert.equal(await themeTab.locator('html').getAttribute('data-theme'), 'arcade');
  await page.getByLabel('Theme', {exact:true}).selectOption('fieldnotes');
  await themeTab.waitForFunction(() => document.documentElement.dataset.theme === 'fieldnotes');
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).backgroundColor), defaultPaper);
  await page.evaluate(() => localStorage.setItem('fieldnotes.theme', 'unknown-theme'));
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(), 'fieldnotes');
  await themeTab.close();
  // Storage restrictions must not prevent switching the current page's theme.
  await page.evaluate(() => {
    window.originalSetItem = Storage.prototype.setItem;
    Storage.prototype.setItem = () => {throw new DOMException('Storage blocked', 'SecurityError');};
  });
  await page.getByLabel('Theme', {exact:true}).selectOption('arcade');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'arcade');
  await page.getByText('Theme applied for this page. Browser storage is unavailable, so it could not be saved.').waitFor();
  await page.evaluate(() => {Storage.prototype.setItem = window.originalSetItem;delete window.originalSetItem;});
  await page.getByLabel('Theme', {exact:true}).selectOption('fieldnotes');
  await page.getByRole('button',{name:'Add collaborator',exact:true}).click();
  await dialog().getByLabel('Account email').fill('browser@example.com');
  await dialog().getByRole('button',{name:'Add collaborator',exact:true}).click();await closed();
  await page.getByText('browser@example.com',{exact:true}).waitFor();
  await visitor.reload();await visitor.locator('#content[aria-busy="false"]').waitFor();
  await Promise.all([visitor.waitForNavigation(), visitor.getByLabel('Your garden',{exact:true}).selectOption('00000000-0000-0000-0000-000000000001')]);
  await visitor.locator('#content[aria-busy="false"]').waitFor();
  await visitor.goto(base+'/settings');await visitor.locator('#content[aria-busy="false"]').waitFor();
  assert.equal(await visitor.getByRole('button',{name:'Add collaborator',exact:true}).count(),0);
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await dialog().getByRole('button',{name:'Remove collaborator',exact:true}).click();await closed();
  await visitor.close();
  await go('/strains');
  assert.equal(await page.locator('.strain-card').count(),152);
  assert.equal(await page.locator('.strain-card.is-collected').count(),0);
  await page.getByLabel('Find a variety or strain',{exact:true}).fill('Blue Dream');
  await page.getByRole('link',{name:'Blue Dream · Not collected',exact:true}).click();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  assert.equal(await page.locator('.lineage-node').count(),3);
  await page.getByRole('button',{name:'♡ Add to wishlist',exact:true}).click();
  await page.getByText('Wishlist updated.',{exact:true}).waitFor();
  await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
  await page.getByRole('link',{name:'Blue Dream · Wanted',exact:true}).waitFor();
  await page.getByRole('button',{name:'✦ Mark collected',exact:true}).click();
  await page.getByText('Strain collected. Your card is unlocked.',{exact:true}).waitFor();
  assert.equal(await page.locator('.strain-card.is-collected').count(),1);
  await go('/strains');
  await page.getByRole('button',{name:'+ Add a strain',exact:true}).click();
  await dialog().getByLabel('Strain name',{exact:true}).fill('Browser cross');
  await dialog().getByLabel('Species',{exact:true}).fill('Test plant');
  await dialog().getByLabel('Collection status',{exact:true}).selectOption('wanted');
  await dialog().getByLabel('Parent 1',{exact:true}).selectOption({label:'Blue Dream'});
  await dialog().getByLabel('Parent 2',{exact:true}).selectOption({label:'Gelato'});
  await dialog().getByRole('button',{name:'Save strain',exact:true}).click();await closed();
  await page.getByLabel('Find a variety or strain',{exact:true}).fill('Browser cross');
  await page.getByRole('link',{name:'Browser cross · Wanted',exact:true}).click();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  await page.getByLabel('Generations',{exact:true}).selectOption('3');
  assert.ok(await page.locator('.lineage-node').count()>=7);
  await page.getByRole('button',{name:'Zoom in ancestry',exact:true}).click();
  await page.getByRole('button',{name:'Fit graph',exact:true}).click();
  await page.screenshot({path:join(artifacts,'strain-ancestry-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Ancestry detail overflows mobile');
  await page.getByRole('button',{name:'Fit graph',exact:true}).click();
  await page.screenshot({path:join(artifacts,'strain-ancestry-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1050});
  await page.getByRole('link',{name:'Explore Blue Dream ancestry',exact:true}).click();
  await page.locator('h1').filter({hasText:'Blue Dream'}).waitFor();
  await go('/strains');
  await page.getByLabel('Show cards',{exact:true}).selectOption('wanted');
  assert.equal(await page.locator('.strain-card').count(),1);
  await page.getByLabel('Show cards',{exact:true}).selectOption('all');
  await page.screenshot({path:join(artifacts,'strain-collection-desktop.png'),fullPage:false});
  await page.getByRole('link',{name:'Cross planner',exact:true}).click();
  await page.getByRole('heading',{name:'Cross planner',exact:true}).waitFor();
  await page.getByRole('button',{name:'+ Plan a cross',exact:true}).first().click();
  await dialog().getByLabel('Working name',{exact:true}).fill('Browser planned cross');
  await dialog().getByLabel('Parent 1',{exact:true}).selectOption({label:'Blue Dream'});
  await dialog().getByLabel('Parent 2',{exact:true}).selectOption({label:'Gelato'});
  await dialog().getByLabel('Species',{exact:true}).fill('Cannabis');
  await dialog().getByLabel('Plan notes',{exact:true}).fill('Keep these parent records together.');
  assert.match(await page.locator('#cross-preview').textContent(),/Blue Dream × Gelato → Browser planned cross/);
  await dialog().getByRole('button',{name:'Save plan',exact:true}).click();await closed();
  await page.locator('.cross-plan h2').filter({hasText:'Browser planned cross'}).waitFor();
  await page.reload();await page.locator('.cross-plan').waitFor();
  await page.getByRole('button',{name:'Edit plan',exact:true}).click();
  await dialog().getByLabel('Plan notes',{exact:true}).fill('Updated plan notes.');
  await dialog().getByRole('button',{name:'Save plan',exact:true}).click();await closed();
  await page.getByText('Updated plan notes.',{exact:true}).waitFor();
  await page.screenshot({path:join(artifacts,'cross-planner-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Cross planner overflows mobile');
  await page.screenshot({path:join(artifacts,'cross-planner-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Edit plan',exact:true}).click();
  await page.screenshot({path:join(artifacts,'cross-editor-mobile.png')});
  const crossOverflow=await dialog().evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth,wide:[...el.querySelectorAll('*')].filter(child=>child.getBoundingClientRect().right>el.getBoundingClientRect().right).map(child=>[child.tagName,child.className,child.getBoundingClientRect().width])}));
  assert.ok(crossOverflow.scroll<=crossOverflow.width,`Cross editor overflows mobile: ${JSON.stringify(crossOverflow)}`);
  await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
  await page.getByRole('button',{name:'Create strain',exact:true}).click();
  assert.equal(await dialog().getByLabel('Strain notes',{exact:true}).inputValue(),'Updated plan notes.');
  await dialog().getByLabel('Strain name',{exact:true}).fill('Browser realized cross');
  await dialog().getByRole('button',{name:'Create strain',exact:true}).click();await closed();
  await page.locator('h1').filter({hasText:'Browser realized cross'}).waitFor();
  await page.getByRole('link',{name:'Browser realized cross · Collected',exact:true}).waitFor();
  assert.ok(await page.locator('.lineage-node').count()>=7);
  await go('/strains?view=crosses');
  await page.getByRole('link',{name:'View strain ↗',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Create strain',exact:true}).count(),0);
  await page.setViewportSize({width:1440,height:1050});
  await go('/seeds');
  await page.getByRole('button',{name:'+ Add your first seeds',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tomato <seed>');
  await dialog().getByLabel('Variety',{exact:true}).fill("O'Brien's Purple");
  await dialog().getByLabel('Quantity on hand').fill('3');
  await dialog().getByLabel('Supplier').fill('Seed library');
  await dialog().getByLabel('Purchase year').fill('2026');
  await dialog().getByLabel('Storage location').fill('Fridge');
  await dialog().getByLabel('Notes',{exact:true}).fill('Sow indoors.');
  await dialog().getByLabel('Strain',{exact:true}).fill('Typed browser strain');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByText('3 packets',{exact:true}).waitFor();
  await page.getByRole('link',{name:'◇ Typed browser strain',exact:true}).waitFor();
  await uploadAndDelete();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Quantity on hand').fill('0');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Out of stock',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Seed inventory overflows mobile viewport');
  await page.screenshot({path:join(artifacts,'seeds-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tomato <seed>',exact:true}).waitFor();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Your next season starts here',exact:true}).waitFor();
  await page.setViewportSize({width:1440,height:1050});
  await go('/plants');
  await page.getByRole('button',{name:'+ Add your first plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Monstera');
  await dialog().getByLabel('Species or variety').fill('Monstera deliciosa');
  await dialog().getByLabel('Strain',{exact:true}).fill('Browser cross');
  await dialog().getByLabel('Plant notes').fill('New leaves near the grow light.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByRole('heading',{name:'Photo history',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Ancestry',exact:true}).waitFor();
  await page.getByRole('link',{name:'◇ Browser cross',exact:true}).waitFor();
  await uploadAndDelete('Monstera');
  await go('/plants');
  await page.getByRole('button',{name:'+ Add a plant',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Pothos');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/journal');
  await page.getByRole('button',{name:'+ Add an entry',exact:true}).click();
  await dialog().getByLabel('Entry type').selectOption('watering');
  await dialog().getByLabel('Monstera',{exact:true}).check();
  await dialog().getByLabel('Pothos',{exact:true}).check();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. New leaf on the monstera.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Watered both plants by hand. New leaf on the monstera.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Observation').fill('Watered both plants by hand. Soil drains well.');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await go('/photos');
  await page.getByRole('button',{name:'▧ Capture now',exact:true}).click();
  await page.locator('.photo-card img').waitFor();
  assert.equal(await page.locator('.photo-card .plant-tags .badge').count(),2);
  await page.getByRole('button',{name:'Link plants',exact:true}).click();
  await dialog().getByLabel('Pothos',{exact:true}).uncheck();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.waitForFunction(()=>document.querySelectorAll('.photo-card .plant-tags .badge').length===1);
  await go('/calendar');
  await page.locator('.day.today').click();
  await page.locator('#day-events').getByText('Watered both plants by hand. Soil drains well.',{exact:true}).first().waitFor();
  await page.getByLabel('Filter by event type').selectOption('photo');
  await page.waitForFunction(()=>document.querySelectorAll('#day-events .timeline li').length===1);
  await page.screenshot({path:join(artifacts,'calendar-desktop.png'),fullPage:true});
  await go('/environment');
  assert.equal(await page.locator('svg.chart').count(),2);
  await page.getByLabel('Reading range').selectOption('168');
  await go('/equipment');
  await page.getByRole('button',{name:'+ Add outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Tent light');
  await dialog().getByRole('button',{name:'Add outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Tent light',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Enable daily schedule').isChecked(),false);
  await page.getByRole('button',{name:'On…',exact:true}).click();
  await dialog().getByRole('button',{name:'Apply override',exact:true}).click();await closed();
  await page.getByText('Output on',{exact:true}).waitFor({timeout:35000});
  await page.getByRole('button',{name:'Resume schedule',exact:true}).click();
  await page.getByText('Output off',{exact:true}).waitFor({timeout:35000});
  await page.getByLabel('On at').fill('20:00');
  await page.getByLabel('Off at').fill('06:00');
  await page.getByRole('button',{name:'Save schedule',exact:true}).click();
  await page.getByText('Schedule saved. It will apply on the next control cycle.').waitFor();
  await page.getByRole('button',{name:'Edit outlet',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Grow light');
  await dialog().getByRole('button',{name:'Save outlet',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Grow light',exact:true}).waitFor();
  await go('/settings');
  await page.getByLabel('Take one photo every day').check();
  await page.getByLabel('Capture time').fill('13:00');
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByText('Settings saved.',{exact:true}).waitFor();
  await go('/');
  await page.screenshot({path:join(artifacts,'overview-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  for(const path of ['/','/plants','/strains','/journal','/calendar','/photos','/environment','/equipment','/settings']) {
    await go(path);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`Mobile overflow on ${path}`);
  }
  await go('/calendar');await page.screenshot({path:join(artifacts,'calendar-mobile.png'),fullPage:true});
  // Seed vault: packet metadata, pending results, and plant provenance.
  await go('/seeds');
  await page.getByRole('button',{name:'+ Add your first seeds',exact:true}).click();
  await dialog().getByLabel('Name',{exact:true}).fill('Vault tomato');
  await dialog().getByLabel('Breeder',{exact:true}).fill('Community breeder');
  await dialog().getByLabel('Acquired on',{exact:true}).fill('2026-09-27');
  await dialog().getByLabel('Packet / lot label',{exact:true}).fill('Lot 01');
  await dialog().getByLabel('Strain',{exact:true}).fill('Browser cross');
  assert.ok(await dialog().evaluate(el=>el.scrollWidth<=el.clientWidth),'Packet form overflows mobile viewport');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByLabel('Find a packet',{exact:true}).fill('community');
  await page.getByRole('link',{name:'Open packet ↗',exact:true}).click();
  await page.getByRole('heading',{name:'Origins & storage',exact:true}).waitFor();
  const vaultUrl=new URL(page.url()).pathname+new URL(page.url()).search;
  await page.getByText('Acquired: Sep 27, 2026',{exact:true}).waitFor();
  await page.getByRole('button',{name:'+ Record attempt',exact:true}).click();
  await dialog().getByLabel('Started on',{exact:true}).fill('2026-09-27');
  await dialog().getByLabel('Seeds sown',{exact:true}).fill('4');
  await dialog().getByLabel('Attempt notes',{exact:true}).fill('First batch <notes>');
  assert.ok(await dialog().evaluate(el=>el.scrollWidth<=el.clientWidth),'Attempt form overflows mobile viewport');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('Pending',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit attempt',exact:true}).click();
  await dialog().getByLabel('Seeds germinated',{exact:true}).fill('3');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'75% germinated',exact:true}).waitFor();
  await page.getByRole('button',{name:'Add plant from attempt',exact:true}).click();
  assert.equal(await dialog().getByLabel('Strain',{exact:true}).inputValue(),'Browser cross');
  assert.equal(await dialog().getByLabel('Seed packet',{exact:true}).locator('option:checked').textContent(),'Vault tomato · Lot 01');
  assert.match(await dialog().getByLabel('Germination attempt',{exact:true}).locator('option:checked').textContent(),/4 sown/);
  await dialog().getByLabel('Name',{exact:true}).fill('Vault seedling');
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'♧ Vault seedling',exact:true}).click();
  await page.getByRole('heading',{name:'Seed origin',exact:true}).waitFor();
  await page.reload();await page.getByRole('heading',{name:'Seed origin',exact:true}).waitFor();
  await page.getByRole('link',{name:'❧ Vault tomato · Lot 01 ↗',exact:true}).click();
  await page.getByRole('heading',{name:'Plants from this packet',exact:true}).waitFor();
  await page.screenshot({path:join(artifacts,'seed-vault-mobile.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Packet detail overflows mobile viewport');
  // Existing plants can be linked to a packet without assigning an attempt.
  await go('/plants');await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByRole('button',{name:'Edit plant',exact:true}).click();
  await dialog().getByLabel('Seed packet',{exact:true}).selectOption({label:'Vault tomato · Lot 01'});
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByText('No germination attempt linked.',{exact:true}).waitFor();
  const appearanceTab=await context.newPage();
  await appearanceTab.goto(base+'/login');
  for (const theme of themeIds.slice(1)) {
    await go('/settings');
    await page.getByLabel('Theme', {exact:true}).selectOption(theme);
    await appearanceTab.waitForFunction(theme=>document.documentElement.dataset.theme===theme,theme);
    await page.reload();await page.locator('#content[aria-busy="false"]').waitFor();
    assert.equal(await page.getByLabel('Theme', {exact:true}).inputValue(),theme);
    for (const width of [1440,390]) {
      await page.setViewportSize({width,height:width===390?844:1050});
      for (const path of ['/','/plants','/seeds',vaultUrl,'/strains','/strains?view=crosses','/journal','/calendar','/photos','/environment','/equipment','/settings']) {
        await go(path);
        assert.equal(await page.locator('html').getAttribute('data-theme'),theme);
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${theme} overflow at ${width}px on ${path}`);
        if (['/','/strains','/settings'].includes(path)) {
          await page.screenshot({path:join(artifacts,`${theme}-${path.slice(1)||'overview'}-${width}.png`),fullPage:path!=='/strains'});
        }
      }
      await go('/strains');
      await page.getByRole('button',{name:'Add starter collections',exact:true}).click();
      await dialog().getByRole('checkbox',{name:'Vegetables',exact:true}).waitFor();
      assert.ok(await dialog().evaluate(el=>el.scrollWidth<=el.clientWidth),`${theme} catalog choices overflow at ${width}px`);
      await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
      await go('/plants');
      await page.getByRole('button',{name:'+ Add a plant',exact:true}).click();
      await dialog().waitFor({state:'visible'});
      assert.ok(await dialog().evaluate(el=>el.scrollWidth<=el.clientWidth),`${theme} dialog overflow at ${width}px`);
      await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await closed();
    }
  }
  await appearanceTab.close();
  await go('/plants');
  await page.locator('.plant-card').filter({has:page.getByRole('link',{name:'Monstera',exact:true})}).getByRole('button',{name:'Edit',exact:true}).click();
  await dialog().getByLabel('Archive plant (keep its history)').check();
  await dialog().getByRole('button',{name:'Save',exact:true}).click();await closed();
  await page.getByRole('link',{name:'Monstera',exact:true}).click();
  await page.getByText('Archived · history retained',{exact:true}).waitFor();
  await page.getByText('Watered both plants by hand. Soil drains well.',{exact:true}).waitFor();
  await go('/photos');
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await dialog().getByRole('button',{name:'Delete permanently',exact:true}).click();await closed();
  await page.getByRole('heading',{name:'Watch the changes unfold',exact:true}).waitFor();
  assert.deepEqual(errors,[],`Browser errors: ${errors.join('\n')}`);
  console.log(`Browser workflows passed on desktop and mobile. Screenshots: ${artifacts}`);
} catch(error) {
  console.error(serverLog);
  throw error;
} finally {
  await browser?.close();
  server.kill('SIGTERM');
  await new Promise(r=>server.exitCode===null?server.once('exit',r):r());
}
