-- Existing records remain in the original owner's garden. The reserved account
-- cannot be claimed through signup; activate it with --set-password.
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT, created_at INTEGER NOT NULL);
CREATE TABLE gardens (id TEXT PRIMARY KEY, name TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES users(id));
CREATE TABLE garden_members (garden_id TEXT NOT NULL REFERENCES gardens(id), user_id TEXT NOT NULL REFERENCES users(id), PRIMARY KEY(garden_id,user_id));
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), garden_id TEXT NOT NULL REFERENCES gardens(id), expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
INSERT INTO users(id,email,created_at) VALUES('00000000-0000-0000-0000-000000000002','ally.rippley@gmail.com',0);
INSERT INTO gardens(id,name,owner_id) VALUES('00000000-0000-0000-0000-000000000001','Ally’s garden','00000000-0000-0000-0000-000000000002');
INSERT INTO garden_members(garden_id,user_id) VALUES('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002');
ALTER TABLE plants ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX plants_garden ON plants(garden_id);
ALTER TABLE entries ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX entries_garden ON entries(garden_id);
ALTER TABLE photos ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX photos_garden ON photos(garden_id);
ALTER TABLE readings ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX readings_garden ON readings(garden_id);
ALTER TABLE devices ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX devices_garden ON devices(garden_id);
ALTER TABLE events ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX events_garden ON events(garden_id);
ALTER TABLE seeds ADD garden_id TEXT NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001';
CREATE INDEX seeds_garden ON seeds(garden_id);
CREATE TABLE garden_settings (garden_id TEXT PRIMARY KEY REFERENCES gardens(id), timezone TEXT NOT NULL DEFAULT 'America/Chicago', photo_enabled INTEGER NOT NULL DEFAULT 0, photo_time TEXT NOT NULL DEFAULT '12:00');
INSERT INTO garden_settings(garden_id,timezone,photo_enabled,photo_time) SELECT '00000000-0000-0000-0000-000000000001',timezone,photo_enabled,photo_time FROM settings;
CREATE TRIGGER plants_garden_insert BEFORE INSERT ON plants WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER plants_garden_update BEFORE UPDATE OF garden_id ON plants WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER entries_garden_insert BEFORE INSERT ON entries WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER entries_garden_update BEFORE UPDATE OF garden_id ON entries WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER photos_garden_insert BEFORE INSERT ON photos WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER photos_garden_update BEFORE UPDATE OF garden_id ON photos WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER readings_garden_insert BEFORE INSERT ON readings WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER readings_garden_update BEFORE UPDATE OF garden_id ON readings WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER devices_garden_insert BEFORE INSERT ON devices WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER devices_garden_update BEFORE UPDATE OF garden_id ON devices WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER events_garden_insert BEFORE INSERT ON events WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER events_garden_update BEFORE UPDATE OF garden_id ON events WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER seeds_garden_insert BEFORE INSERT ON seeds WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER seeds_garden_update BEFORE UPDATE OF garden_id ON seeds WHEN NOT EXISTS(SELECT 1 FROM gardens WHERE id=NEW.garden_id) BEGIN SELECT RAISE(ABORT,'Unknown garden'); END;
CREATE TRIGGER gardens_retain BEFORE DELETE ON gardens BEGIN SELECT RAISE(ABORT,'Garden deletion is not supported'); END;
